### ISSUE TITLE
To credit or not to credit ...

### ISSUE THREAD

**Issue by alex-strobel** [alex-strobel/DPP-LabManual#4]
I guess, the title of this issue exactly points to the problem: If we write Wiki entries or manuals, it is not for the purpose of being "fitter, happier, more productive" (to quote Radiohead) and, hence, deserve credit. We write them entries/manuals because we know something that may be of use to others (in the team or - as this is a public repository - elsewhere). But we also might be wrong in our suggested approach. So, I would rather go for the term *attribution*: Some named person(s) wrote down some procedure, elaborated on some issue, but perhaps made mistakes in doing so. Yet, we could also go for unnamed contributions to this repository which would mean that we as a team are collectively responsible for all the suggestions made here. It would make writing and revising an entry/manual much easier (because we do not need to state who wrote what and when). At the same time, it would make writing and revising an entry more complicated because we could not write "In my experience, ..." or "I suggest to", but would require to have a collective decision on some topic, which is the main idea of this LabManual, but may be counterproductive in some instance (such as when you write a Wiki entry on, e.g., multiple testing because you read a lot about this issue and really know better, but the rest of the team argues that this would be a too stringent correction).

So we need to come to a decision of whether or when we *attribute* entries to one or more persons or have an entry unnamed/unattributed.

**Comment by ChScheffel** [comment]
I would suggest a hybrid approach: Some topics are collective decisions, how we want to deal with an issue in our group (e.g., _open data_). We would not put a name there, so it is clear that it is a consensus between us.  Other topics represent the expertise of a single person (e.g. _renv_ - Alex; _genes_ and _genetic scores_ - Anne) , of which the others may have no expertise at all. This is made clear by the fact that this topic is attributed to the person.

**Comment by JZerna** [comment]
I agree with Christoph. It can also change over time - if someone is an expert on one topic now, let's say a certain software, and others use their manual entry as a starting point but then get comfortable with the software over time and find better workflows, the entry can be changed from 'solitary' to 'consensus'.

**Comment by angaertner** [comment]
I agree. If someone writes an entry on a certain workflow (e.g. RedCap) and I have questions on that, I find it easier if there is a name of the person I can contact. However, I think the names are also visible in the history of an entry. So, I think it is important to see who wrote the files. Besides, if the purpose is solely to give someone credit, I think it's better to do than not to do in cases where it makes sense (single expertise vs. collective consensus).
